name: Test project

on: push

jobs:
  test-job:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Check codestyle
        run: find . -name "*.[ch]pp" | xargs clang-format -i && git diff --exit-code

      - name: Test application
        run: make test    
