name: Test project

on: push

jobs:
  test-job:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Check codestyle
        run: make format && git diff --exit-code

      - name: Test application
        run: make test    
